const gameCards = [
  { targetWord: "Jollof Rice", forbiddenWords: ["Party", "Tomato", "Orange"] },
  { targetWord: "Nollywood", forbiddenWords: ["Movie", "Film", "Actor"] },
  { targetWord: "Lagos", forbiddenWords: ["Traffic", "City", "Eko"] },
  {
    targetWord: "Fela Kuti",
    forbiddenWords: ["Music", "Afrobeat", "Saxophone"],
  },
  { targetWord: "Suya", forbiddenWords: ["Meat", "Skewer", "Spice"] },
  { targetWord: "Agbada", forbiddenWords: ["Buba", "Sokoto", "Grand"] },
  { targetWord: "Harmattan", forbiddenWords: ["Dry", "Season", "Dust"] },
  { targetWord: "Okada", forbiddenWords: ["Motorcycle", "Bike", "Transport"] },
  { targetWord: "Puff Puff", forbiddenWords: ["Dough", "Snack", "Fried"] },
  { targetWord: "Chin Chin", forbiddenWords: ["Snack", "Hard", "Flour"] },
  { targetWord: "Eba", forbiddenWords: ["Garri", "Swallow", "Soup"] },
  { targetWord: "Pounded Yam", forbiddenWords: ["Iyan", "Mortar", "Tuber"] },
  { targetWord: "Davido", forbiddenWords: ["OBO", "Music", "30BG"] },
  { targetWord: "Wizkid", forbiddenWords: ["Starboy", "Music", "Ojuelegba"] },
  {
    targetWord: "Burna Boy",
    forbiddenWords: ["African Giant", "Odogwu", "Grammy"],
  },
  { targetWord: "Super Eagles", forbiddenWords: ["Football", "Team", "Green"] },
  {
    targetWord: "Wole Soyinka",
    forbiddenWords: ["Nobel", "Author", "Playwright"],
  },
  {
    targetWord: "Chimamanda Adichie",
    forbiddenWords: ["Author", "Feminist", "Writer"],
  },
  { targetWord: "Danfo", forbiddenWords: ["Bus", "Yellow", "Conductor"] },
  {
    targetWord: "Pidgin English",
    forbiddenWords: ["Language", "Broken", "Speak"],
  },
  { targetWord: "Aso Rock", forbiddenWords: ["President", "Abuja", "Villa"] },
  { targetWord: "Zuma Rock", forbiddenWords: ["Abuja", "Face", "Monolith"] },
  { targetWord: "Gele", forbiddenWords: ["Head-tie", "Fabric", "Women"] },
  { targetWord: "Owambe", forbiddenWords: ["Party", "Celebration", "Spray"] },
  { targetWord: "Boli", forbiddenWords: ["Plantain", "Roasted", "Fish"] },
  { targetWord: "Akara", forbiddenWords: ["Beans", "Cake", "Fried"] },
  { targetWord: "Moi Moi", forbiddenWords: ["Beans", "Pudding", "Steamed"] },
  { targetWord: "Egusi", forbiddenWords: ["Soup", "Melon", "Seed"] },
  {
    targetWord: "Keke Napep",
    forbiddenWords: ["Tricycle", "Yellow", "Transport"],
  },
  { targetWord: "Shea Butter", forbiddenWords: ["Ori", "Cream", "Skin"] },
  { targetWord: "Palm Wine", forbiddenWords: ["Drink", "Tree", "Tapper"] },
  { targetWord: "Ankara", forbiddenWords: ["Fabric", "Wax", "Print"] },
  {
    targetWord: "Talking Drum",
    forbiddenWords: ["Gangan", "Instrument", "Yoruba"],
  },
  { targetWord: "NEPA", forbiddenWords: ["Light", "Power", "Blackout"] },
  { targetWord: "Go-slow", forbiddenWords: ["Traffic", "Jam", "Hold-up"] },
  { targetWord: "Oga", forbiddenWords: ["Boss", "Master", "Chief"] },
  { targetWord: "Wahala", forbiddenWords: ["Trouble", "Problem", "Stress"] },
  { targetWord: "Sisi", forbiddenWords: ["Girl", "Lady", "Young"] },
  { targetWord: "Buka", forbiddenWords: ["Restaurant", "Food", "Local"] },
  { targetWord: "Garri", forbiddenWords: ["Cassava", "Flakes", "Drink"] },
  {
    targetWord: "Iro and Buba",
    forbiddenWords: ["Wrapper", "Blouse", "Yoruba"],
  },
  { targetWord: "Shaku Shaku", forbiddenWords: ["Dance", "Legwork", "Zanku"] },
  { targetWord: "Aliko Dangote", forbiddenWords: ["Richest", "Man", "Cement"] },
  { targetWord: "Nkwobi", forbiddenWords: ["Cowleg", "Spicy", "Igbo"] },
  {
    targetWord: "Abacha",
    forbiddenWords: ["African Salad", "Cassava", "Ugba"],
  },
  { targetWord: "Zobo", forbiddenWords: ["Drink", "Red", "Hibiscus"] },
  {
    targetWord: "Tiwa Savage",
    forbiddenWords: ["Queen", "Afrobeats", "Singer"],
  },
  {
    targetWord: "Yemi Alade",
    forbiddenWords: ["Mama Africa", "Johnny", "Female"],
  },
  {
    targetWord: "Olumo Rock",
    forbiddenWords: ["Abeokuta", "Mountain", "Egba"],
  },
  { targetWord: "Afrobeats", forbiddenWords: ["Music", "Genre", "Fela"] },
  { targetWord: "IJGB", forbiddenWords: ["Abroad", "Returnee", "Diaspora"] },
  {
    targetWord: "Detty December",
    forbiddenWords: ["Party", "December", "Lagos"],
  },
  {
    targetWord: "Nepo Baby",
    forbiddenWords: ["Privilege", "Parents", "Famous"],
  },
  { targetWord: "Lapo Baby", forbiddenWords: ["Lekki", "Rich", "Spoiled"] },
  { targetWord: "Rema", forbiddenWords: ["Calm Down", "Mavin", "Benin"] },
  { targetWord: "Asake", forbiddenWords: ["Mr Money", "YBNL", "Olamide"] },
  { targetWord: "Tems", forbiddenWords: ["Essence", "Grammy", "Female"] },
  { targetWord: "Olamide", forbiddenWords: ["YBNL", "Baddo", "Indigenous"] },
  { targetWord: "Ayra Starr", forbiddenWords: ["Rush", "Mavin", "Young"] },
  { targetWord: "Fireboy DML", forbiddenWords: ["Peru", "YBNL", "Jealous"] },
  {
    targetWord: "Omah Lay",
    forbiddenWords: ["Godly", "Port Harcourt", "Singer"],
  },
  { targetWord: "Simi", forbiddenWords: ["Duduke", "Adekunle", "Voice"] },
  {
    targetWord: "Adekunle Gold",
    forbiddenWords: ["Orente", "Simi", "Highlife"],
  },
  { targetWord: "Falz", forbiddenWords: ["Lawyer", "Funny", "Bop Daddy"] },
  { targetWord: "Mr Eazi", forbiddenWords: ["Leg Over", "Banku", "Temi"] },
  { targetWord: "Tekno", forbiddenWords: ["Pana", "Skeletun", "Producer"] },
  { targetWord: "Kizz Daniel", forbiddenWords: ["Buga", "Woju", "Cough"] },
  { targetWord: "Seyi Vibez", forbiddenWords: ["Street", "Singer", "Fuji"] },
  { targetWord: "Zinoleesky", forbiddenWords: ["Marlian", "Naira", "Singer"] },
  { targetWord: "Mohbad", forbiddenWords: ["Marlian", "Singer", "Late"] },
  {
    targetWord: "Naira Marley",
    forbiddenWords: ["Marlian", "Soapy", "Controversy"],
  },
  { targetWord: "Zlatan", forbiddenWords: ["Zanku", "Rapper", "Legwork"] },
  {
    targetWord: "Bella Shmurda",
    forbiddenWords: ["Cash App", "Singer", "Street"],
  },
  { targetWord: "Ruger", forbiddenWords: ["Bounce", "Eyepatch", "Singer"] },
  { targetWord: "BNXN", forbiddenWords: ["Buju", "Finesse", "Singer"] },
  { targetWord: "Victony", forbiddenWords: ["Wheelchair", "Singer", "Soweto"] },
  { targetWord: "Joeboy", forbiddenWords: ["Baby", "emPawa", "Alcohol"] },
  { targetWord: "Oxlade", forbiddenWords: ["Away", "Singer", "KU LO SA"] },
  { targetWord: "DJ Cuppy", forbiddenWords: ["Pink", "Otedola", "DJ"] },
  { targetWord: "Mayorkun", forbiddenWords: ["Mayor", "Of Lagos", "Geng"] },
  { targetWord: "Peruzzi", forbiddenWords: ["Majesty", "DMW", "Songwriter"] },
  {
    targetWord: "Blaqbonez",
    forbiddenWords: ["Sex Over Love", "Rapper", "Chocolate City"],
  },
  { targetWord: "Vector", forbiddenWords: ["Viper", "Rapper", "Lafiaji"] },
  {
    targetWord: "MI Abaga",
    forbiddenWords: ["Chocolate City", "Rapper", "Chairman"],
  },
  { targetWord: "Ice Prince", forbiddenWords: ["Oleku", "Rapper", "Jos"] },
  {
    targetWord: "Jesse Jagz",
    forbiddenWords: ["Chocolate City", "Rapper", "Jos"],
  },
  { targetWord: "Ycee", forbiddenWords: ["Juice", "Rapper", "Tinny"] },
  { targetWord: "Phyno", forbiddenWords: ["Igbo", "Rapper", "Enugu"] },
  { targetWord: "Flavour", forbiddenWords: ["Highlife", "Nwa Baby", "Enugu"] },
  {
    targetWord: "Patoranking",
    forbiddenWords: ["Reggae", "Dancehall", "Alubarika"],
  },
  { targetWord: "Timaya", forbiddenWords: ["Dem Mama", "Plantain", "Bayelsa"] },
  {
    targetWord: "2Baba",
    forbiddenWords: ["African Queen", "Legend", "Plantashun"],
  },
  { targetWord: "Don Jazzy", forbiddenWords: ["Mavin", "Producer", "Mohits"] },
  {
    targetWord: "ID Cabasa",
    forbiddenWords: ["Producer", "Coded Tunes", "Olamide"],
  },
  { targetWord: "Sarz", forbiddenWords: ["Beat", "Producer", "Paigon"] },
  { targetWord: "Pheelz", forbiddenWords: ["Producer", "Finesse", "BNXN"] },
  {
    targetWord: "Young Jonn",
    forbiddenWords: ["Producer", "Dada", "Chocolate City"],
  },
  { targetWord: "Rexxie", forbiddenWords: ["Producer", "Grammy", "KPK"] },
  { targetWord: "P-Square", forbiddenWords: ["Twins", "Peter", "Paul"] },
  { targetWord: "Psquare", forbiddenWords: ["Personally", "Twins", "Breakup"] },
  {
    targetWord: "D'banj",
    forbiddenWords: ["Kokomaster", "Oliver Twist", "Harmonica"],
  },
  { targetWord: "Banky W", forbiddenWords: ["EME", "Yes/No", "Actor"] },
  { targetWord: "Wande Coal", forbiddenWords: ["Bumper", "Mushin", "2 Match"] },
  { targetWord: "Skales", forbiddenWords: ["Shake Body", "EME", "Rapper"] },
  { targetWord: "9ice", forbiddenWords: ["Gongo Aso", "Ancestor", "Ogara"] },
  { targetWord: "Ruggedman", forbiddenWords: ["Ruggedy", "Baba", "Rapper"] },
  {
    targetWord: "Eedris Abdulkareem",
    forbiddenWords: ["Jaga Jaga", "Rapper", "50 Cent"],
  },
  {
    targetWord: "Tony Tetuila",
    forbiddenWords: ["My Car", "Remedies", "Ondo"],
  },
  {
    targetWord: "Plantashun Boiz",
    forbiddenWords: ["2Baba", "Blackface", "Faze"],
  },
  { targetWord: "Styl-Plus", forbiddenWords: ["Olufunmi", "Group", "Runaway"] },
  { targetWord: "Bracket", forbiddenWords: ["Yori Yori", "Duo", "Group"] },
  { targetWord: "PJ Morton", forbiddenWords: ["Maroon 5", "America", "Lagos"] },
  {
    targetWord: "Bez",
    forbiddenWords: ["That Stupid Song", "Alternative", "Singer"],
  },
  { targetWord: "Johnny Drille", forbiddenWords: ["Mavin", "Guitar", "Folk"] },
  { targetWord: "Chike", forbiddenWords: ["Running", "Voice", "Project Fame"] },
  { targetWord: "Ladipoe", forbiddenWords: ["Mavin", "Rapper", "Feeling"] },
  { targetWord: "A-Q", forbiddenWords: ["Rapper", "Chocolate City", "MI"] },
  {
    targetWord: "Ckay",
    forbiddenWords: ["Love Nwantiti", "Producer", "Chocolate City"],
  },
  { targetWord: "Crayon", forbiddenWords: ["Mavin", "Ijo", "Young"] },
  { targetWord: "Bayanni", forbiddenWords: ["Mavin", "Ta Ta Ta", "Young"] },
  { targetWord: "Magixx", forbiddenWords: ["Mavin", "Love", "Young"] },
  { targetWord: "Boy Spyce", forbiddenWords: ["Mavin", "Innocent", "Young"] },
  {
    targetWord: "Shallipopi",
    forbiddenWords: ["Plutomania", "Benin", "Elon Musk"],
  },
  { targetWord: "Portable", forbiddenWords: ["Zazoo", "Ika", "Controversial"] },
  { targetWord: "Poco Lee", forbiddenWords: ["Dancer", "Hype", "Zlatan"] },
  {
    targetWord: "Kaffy",
    forbiddenWords: ["Dancer", "Choreographer", "Guinness"],
  },
  {
    targetWord: "Shank Comics",
    forbiddenWords: ["Instagram", "Comedian", "Character"],
  },
  {
    targetWord: "Mr Macaroni",
    forbiddenWords: ["Freaky", "Twitter", "Comedian"],
  },
  {
    targetWord: "Sabinus",
    forbiddenWords: ["Something Hooge", "Mr Funny", "Comedian"],
  },
  {
    targetWord: "Broda Shaggi",
    forbiddenWords: ["Comedian", "Mushin", "Character"],
  },
  {
    targetWord: "Sydney Talker",
    forbiddenWords: ["Comedian", "Towel", "Village"],
  },
  {
    targetWord: "Mark Angel",
    forbiddenWords: ["Comedy", "Success", "Emmanuella"],
  },
  {
    targetWord: "Emmanuella",
    forbiddenWords: ["Child", "Comedian", "This is not my real face"],
  },
  {
    targetWord: "Taaooma",
    forbiddenWords: ["Comedian", "Mother", "Characters"],
  },
  {
    targetWord: "Lasisi Elenu",
    forbiddenWords: ["Snap", "Filter", "Comedian"],
  },
  {
    targetWord: "Officer Woos",
    forbiddenWords: ["Police", "Comedy", "Character"],
  },
  {
    targetWord: "Tunde Ednut",
    forbiddenWords: ["Instagram", "Blogger", "Singer"],
  },
  { targetWord: "Linda Ikeji", forbiddenWords: ["Blog", "Gossip", "Blogger"] },
  {
    targetWord: "Noble Igwe",
    forbiddenWords: ["Media", "Influencer", "360Nobs"],
  },
  { targetWord: "Ebuka", forbiddenWords: ["BBNaija", "Host", "Agbada"] },
  { targetWord: "Laycon", forbiddenWords: ["BBNaija", "Rapper", "Winner"] },
  {
    targetWord: "Mercy Eke",
    forbiddenWords: ["BBNaija", "Pepper Dem", "Winner"],
  },
  { targetWord: "Phyna", forbiddenWords: ["BBNaija", "Winner", "Level Up"] },
  { targetWord: "Ilebaye", forbiddenWords: ["BBNaija", "Gen Z", "All Stars"] },
  { targetWord: "Whitemoney", forbiddenWords: ["BBNaija", "Cook", "Selense"] },
  { targetWord: "Pere", forbiddenWords: ["BBNaija", "Military", "General"] },
  { targetWord: "Cross", forbiddenWords: ["BBNaija", "Fitness", "Body"] },
  { targetWord: "BBNaija", forbiddenWords: ["Reality", "Show", "House"] },
  {
    targetWord: "Gulder Ultimate Search",
    forbiddenWords: ["Reality", "Show", "Jungle"],
  },
  { targetWord: "The Johnsons", forbiddenWords: ["Series", "TV", "Family"] },
  {
    targetWord: "Jenifa's Diary",
    forbiddenWords: ["Funke", "Series", "Comedy"],
  },
  {
    targetWord: "Funke Akindele",
    forbiddenWords: ["Jenifa", "Actress", "Box Office"],
  },
  {
    targetWord: "Genevieve Nnaji",
    forbiddenWords: ["Actress", "Lionheart", "Beautiful"],
  },
  {
    targetWord: "Ramsey Nouah",
    forbiddenWords: ["Actor", "Lover Boy", "Handsome"],
  },
  {
    targetWord: "RMD",
    forbiddenWords: ["Richard Mofe-Damijo", "Actor", "Ageless"],
  },
  {
    targetWord: "Omotola Jalade",
    forbiddenWords: ["Actress", "Omosexy", "Beautiful"],
  },
  { targetWord: "Jim Iyke", forbiddenWords: ["Actor", "Bad Boy", "Nollywood"] },
  { targetWord: "Mercy Johnson", forbiddenWords: ["Actress", "Comedy", "Cry"] },
  {
    targetWord: "Rita Dominic",
    forbiddenWords: ["Actress", "Beautiful", "Nollywood"],
  },
  {
    targetWord: "Ini Edo",
    forbiddenWords: ["Actress", "Beautiful", "Nollywood"],
  },
  {
    targetWord: "Kate Henshaw",
    forbiddenWords: ["Actress", "Fitness", "Ageless"],
  },
  {
    targetWord: "Sola Sobowale",
    forbiddenWords: ["King of Boys", "Toyin Tomato", "Actress"],
  },
  { targetWord: "King of Boys", forbiddenWords: ["Eniola", "Kemi", "Movie"] },
  {
    targetWord: "The Wedding Party",
    forbiddenWords: ["Movie", "Wedding", "Comedy"],
  },
  { targetWord: "Sugar Rush", forbiddenWords: ["Movie", "Heist", "EFCC"] },
  {
    targetWord: "Gangs of Lagos",
    forbiddenWords: ["Movie", "Crime", "Amazon"],
  },
  {
    targetWord: "Blood Sisters",
    forbiddenWords: ["Series", "Netflix", "Wedding"],
  },
  { targetWord: "Shanty Town", forbiddenWords: ["Series", "Netflix", "Crime"] },
  {
    targetWord: "Far From Home",
    forbiddenWords: ["Series", "Netflix", "School"],
  },
  {
    targetWord: "Anikulapo",
    forbiddenWords: ["Movie", "Netflix", "Kunle Afolayan"],
  },
  {
    targetWord: "Living in Bondage",
    forbiddenWords: ["Classic", "Movie", "Occult"],
  },
  { targetWord: "Aki and Pawpaw", forbiddenWords: ["Comedy", "Duo", "Small"] },
  { targetWord: "Osita Iheme", forbiddenWords: ["Pawpaw", "Actor", "Small"] },
  { targetWord: "Chinedu Ikedieze", forbiddenWords: ["Aki", "Actor", "Small"] },
  { targetWord: "Mr Ibu", forbiddenWords: ["Comedian", "Actor", "Belly"] },
  {
    targetWord: "Charles Inojie",
    forbiddenWords: ["Actor", "Comedian", "The Johnsons"],
  },
  { targetWord: "Sam Loco Efe", forbiddenWords: ["Actor", "Legend", "Late"] },
  { targetWord: "Pete Edochie", forbiddenWords: ["Igbo", "Actor", "Legend"] },
  {
    targetWord: "Kanayo O. Kanayo",
    forbiddenWords: ["Sacrifice", "Actor", "Meme"],
  },
  {
    targetWord: "Okrika",
    forbiddenWords: ["Bend Down", "Clothes", "Second Hand"],
  },
  {
    targetWord: "Bend Down Select",
    forbiddenWords: ["Okrika", "Thrift", "Clothes"],
  },
  { targetWord: "Tokunbo", forbiddenWords: ["Foreign", "Used", "Car"] },
  { targetWord: "Molue", forbiddenWords: ["Yellow", "Bus", "Old"] },
  { targetWord: "BRT", forbiddenWords: ["Bus", "Blue", "Lagos"] },
  { targetWord: "Uber", forbiddenWords: ["Ride", "App", "Car"] },
  { targetWord: "Bolt", forbiddenWords: ["Ride", "App", "Cheap"] },
  { targetWord: "InDriver", forbiddenWords: ["Ride", "Negotiate", "App"] },
  { targetWord: "Opay", forbiddenWords: ["Bike", "Green", "App"] },
  { targetWord: "Gokada", forbiddenWords: ["Bike", "App", "Banned"] },
  {
    targetWord: "Lekki Toll Gate",
    forbiddenWords: ["Bridge", "Payment", "EndSARS"],
  },
  {
    targetWord: "Third Mainland Bridge",
    forbiddenWords: ["Long", "Lagos", "Bridge"],
  },
  { targetWord: "Eko Bridge", forbiddenWords: ["Bridge", "Lagos", "Island"] },
  {
    targetWord: "Computer Village",
    forbiddenWords: ["Ikeja", "Electronics", "Phones"],
  },
  {
    targetWord: "Balogun Market",
    forbiddenWords: ["Lagos Island", "Fabric", "Crowded"],
  },
  {
    targetWord: "Alaba International",
    forbiddenWords: ["Market", "Electronics", "Ojo"],
  },
  { targetWord: "Idumota", forbiddenWords: ["Market", "Lagos", "Island"] },
  { targetWord: "Yaba", forbiddenWords: ["Market", "Tech", "Lagos"] },
  { targetWord: "Surulere", forbiddenWords: ["Lagos", "Stadium", "Area"] },
  {
    targetWord: "Ikeja City Mall",
    forbiddenWords: ["Shopping", "Mall", "Ikeja"],
  },
  { targetWord: "Palms Mall", forbiddenWords: ["Shopping", "Lekki", "Mall"] },
  { targetWord: "Jara", forbiddenWords: ["Extra", "Bonus", "Free"] },
  { targetWord: "Aso Ebi", forbiddenWords: ["Uniform", "Party", "Fabric"] },
  { targetWord: "Spraying Money", forbiddenWords: ["Naira", "Dance", "Party"] },
  {
    targetWord: "Small Chops",
    forbiddenWords: ["Party", "Snacks", "Assorted"],
  },
  { targetWord: "Amala", forbiddenWords: ["Yam Flour", "Ewedu", "Swallow"] },
  { targetWord: "Ewedu", forbiddenWords: ["Soup", "Green", "Slimy"] },
  { targetWord: "Gbegiri", forbiddenWords: ["Soup", "Beans", "Yellow"] },
  { targetWord: "Ofada Rice", forbiddenWords: ["Local", "Rice", "Stew"] },
  { targetWord: "Ayamase", forbiddenWords: ["Ofada", "Stew", "Green"] },
  { targetWord: "Pepper Soup", forbiddenWords: ["Hot", "Spicy", "Goat"] },
  { targetWord: "Asun", forbiddenWords: ["Goat", "Spicy", "Pepper"] },
  { targetWord: "Isi Ewu", forbiddenWords: ["Goat", "Head", "Igbo"] },
  { targetWord: "Nkwobi", forbiddenWords: ["Cowleg", "Spicy", "Igbo"] },
  {
    targetWord: "Catfish",
    forbiddenWords: ["Fish", "Pepper Soup", "Whiskers"],
  },
  { targetWord: "Point and Kill", forbiddenWords: ["Fresh", "Fish", "Select"] },
  { targetWord: "Agege Bread", forbiddenWords: ["White", "Bread", "Soft"] },
  { targetWord: "Indomie", forbiddenWords: ["Noodles", "Instant", "Blue"] },
  { targetWord: "Gala", forbiddenWords: ["Sausage", "Roll", "Snack"] },
  { targetWord: "La Casera", forbiddenWords: ["Apple", "Drink", "Green"] },
  { targetWord: "Ribena", forbiddenWords: ["Blackcurrant", "Drink", "Purple"] },
  { targetWord: "Maltina", forbiddenWords: ["Malt", "Drink", "Energy"] },
  { targetWord: "Fura da Nono", forbiddenWords: ["Millet", "Milk", "Hausa"] },
  { targetWord: "Kunun", forbiddenWords: ["Drink", "Millet", "White"] },
  { targetWord: "Kilishi", forbiddenWords: ["Meat", "Dried", "Hausa"] },
  { targetWord: "Dankwa", forbiddenWords: ["Sugar Cane", "Snack", "Sweet"] },
  { targetWord: "Groundnut", forbiddenWords: ["Peanut", "Nut", "Roasted"] },
  { targetWord: "Coconut", forbiddenWords: ["Fruit", "White", "Water"] },
  {
    targetWord: "Garden Egg",
    forbiddenWords: ["Vegetable", "Bitter", "White"],
  },
  { targetWord: "Ugwu", forbiddenWords: ["Vegetable", "Green", "Leaves"] },
  { targetWord: "Bitter Leaf", forbiddenWords: ["Vegetable", "Soup", "Green"] },
  { targetWord: "Stockfish", forbiddenWords: ["Fish", "Dry", "Hard"] },
  { targetWord: "Crayfish", forbiddenWords: ["Seafood", "Powder", "Soup"] },
  { targetWord: "Locust Beans", forbiddenWords: ["Iru", "Seasoning", "Smell"] },
  { targetWord: "Maggi", forbiddenWords: ["Cube", "Seasoning", "Taste"] },
  { targetWord: "Yaji", forbiddenWords: ["Spice", "Powder", "Suya"] },
  // --- GLOBAL DECK ---
  {
    category: "global",
    targetWord: "iPhone",
    forbiddenWords: ["Apple", "Phone", "Siri"],
  },
  {
    category: "global",
    targetWord: "Netflix",
    forbiddenWords: ["Movie", "Stream", "Chill"],
  },
  {
    category: "global",
    targetWord: "WhatsApp",
    forbiddenWords: ["Chat", "Message", "Status"],
  },
  {
    category: "global",
    targetWord: "TikTok",
    forbiddenWords: ["Video", "Dance", "China"],
  },
  {
    category: "global",
    targetWord: "Instagram",
    forbiddenWords: ["Photo", "Story", "Meta"],
  },
  {
    category: "global",
    targetWord: "Twitter / X",
    forbiddenWords: ["Tweet", "Elon Musk", "Bird"],
  },
  {
    category: "global",
    targetWord: "Snapchat",
    forbiddenWords: ["Filter", "Ghost", "Streak"],
  },
  {
    category: "global",
    targetWord: "YouTube",
    forbiddenWords: ["Video", "Subscribe", "Google"],
  },
  {
    category: "global",
    targetWord: "Google",
    forbiddenWords: ["Search", "Engine", "Android"],
  },
  {
    category: "global",
    targetWord: "Amazon",
    forbiddenWords: ["Shopping", "Jeff Bezos", "Prime"],
  },
  {
    category: "global",
    targetWord: "Uber",
    forbiddenWords: ["Taxi", "Ride", "Driver"],
  },
  {
    category: "global",
    targetWord: "Tesla",
    forbiddenWords: ["Car", "Electric", "Elon"],
  },
  {
    category: "global",
    targetWord: "PlayStation",
    forbiddenWords: ["Sony", "Game", "Console"],
  },
  {
    category: "global",
    targetWord: "FIFA",
    forbiddenWords: ["Football", "Game", "EA Sports"],
  },
  {
    category: "global",
    targetWord: "Call of Duty",
    forbiddenWords: ["War", "Shooting", "Game"],
  },
  {
    category: "global",
    targetWord: "Candy Crush",
    forbiddenWords: ["Game", "Phone", "Sweet"],
  },
  {
    category: "global",
    targetWord: "Bitcoin",
    forbiddenWords: ["Crypto", "Money", "Digital"],
  },
  {
    category: "global",
    targetWord: "AI / ChatGPT",
    forbiddenWords: ["Robot", "Smart", "OpenAI"],
  },
  {
    category: "global",
    targetWord: "Wi-Fi",
    forbiddenWords: ["Internet", "Connect", "Wireless"],
  },
  {
    category: "global",
    targetWord: "Bluetooth",
    forbiddenWords: ["Connect", "Pair", "Wireless"],
  },
  {
    category: "global",
    targetWord: "Laptop",
    forbiddenWords: ["Computer", "Portable", "Keyboard"],
  },
  {
    category: "global",
    targetWord: "Charger",
    forbiddenWords: ["Phone", "Power", "Battery"],
  },
  {
    category: "global",
    targetWord: "Power Bank",
    forbiddenWords: ["Charge", "Battery", "Portable"],
  },
  {
    category: "global",
    targetWord: "Earbuds / AirPods",
    forbiddenWords: ["Music", "Ear", "Wireless"],
  },
  {
    category: "global",
    targetWord: "Selfie",
    forbiddenWords: ["Photo", "Picture", "Face"],
  },
  {
    category: "global",
    targetWord: "Michael Jackson",
    forbiddenWords: ["King of Pop", "Dance", "Thriller"],
  },
  {
    category: "global",
    targetWord: "Beyoncé",
    forbiddenWords: ["Queen B", "Jay-Z", "Singer"],
  },
  {
    category: "global",
    targetWord: "Rihanna",
    forbiddenWords: ["Umbrella", "Singer", "Barbados"],
  },
  {
    category: "global",
    targetWord: "Drake",
    forbiddenWords: ["Rapper", "Canada", "Hotline Bling"],
  },
  {
    category: "global",
    targetWord: "Justin Bieber",
    forbiddenWords: ["Baby", "Singer", "Canada"],
  },
  {
    category: "global",
    targetWord: "Chris Brown",
    forbiddenWords: ["Singer", "Dance", "Loyal"],
  },
  {
    category: "global",
    targetWord: "Nicki Minaj",
    forbiddenWords: ["Rapper", "Pink", "Barbie"],
  },
  {
    category: "global",
    targetWord: "Cardi B",
    forbiddenWords: ["Rapper", "WAP", "Offset"],
  },
  {
    category: "global",
    targetWord: "Kanye West",
    forbiddenWords: ["Ye", "Kim", "Rapper"],
  },
  {
    category: "global",
    targetWord: "Jay-Z",
    forbiddenWords: ["Rapper", "Beyoncé", "Billionaire"],
  },
  {
    category: "global",
    targetWord: "Eminem",
    forbiddenWords: ["Rapper", "Slim Shady", "White"],
  },
  {
    category: "global",
    targetWord: "50 Cent",
    forbiddenWords: ["Rapper", "In Da Club", "Candy Shop"],
  },
  {
    category: "global",
    targetWord: "Ed Sheeran",
    forbiddenWords: ["Singer", "Shape of You", "Ginger"],
  },
  {
    category: "global",
    targetWord: "Adele",
    forbiddenWords: ["Singer", "Hello", "British"],
  },
  {
    category: "global",
    targetWord: "Bob Marley",
    forbiddenWords: ["Reggae", "Jamaica", "Weed"],
  },
  {
    category: "global",
    targetWord: "Celine Dion",
    forbiddenWords: ["Titanic", "Singer", "Heart"],
  },
  {
    category: "global",
    targetWord: "Whitney Houston",
    forbiddenWords: ["Singer", "Bodyguard", "I Will Always Love You"],
  },
  {
    category: "global",
    targetWord: "Mariah Carey",
    forbiddenWords: ["Singer", "Christmas", "High Note"],
  },
  {
    category: "global",
    targetWord: "Usher",
    forbiddenWords: ["Singer", "Yeah", "Confessions"],
  },
  {
    category: "global",
    targetWord: "Lionel Messi",
    forbiddenWords: ["Football", "Argentina", "GOAT"],
  },
  {
    category: "global",
    targetWord: "Cristiano Ronaldo",
    forbiddenWords: ["CR7", "Portugal", "Football"],
  },
  {
    category: "global",
    targetWord: "Neymar",
    forbiddenWords: ["Brazil", "Football", "PSG"],
  },
  {
    category: "global",
    targetWord: "Kylian Mbappé",
    forbiddenWords: ["France", "Football", "Speed"],
  },
  {
    category: "global",
    targetWord: "Manchester United",
    forbiddenWords: ["Red Devils", "Club", "Old Trafford"],
  },
  {
    category: "global",
    targetWord: "Chelsea",
    forbiddenWords: ["Blues", "London", "Club"],
  },
  {
    category: "global",
    targetWord: "Arsenal",
    forbiddenWords: ["Gunners", "London", "Club"],
  },
  {
    category: "global",
    targetWord: "Liverpool",
    forbiddenWords: ["Reds", "Anfield", "Club"],
  },
  {
    category: "global",
    targetWord: "Barcelona",
    forbiddenWords: ["Spain", "Club", "Messi"],
  },
  {
    category: "global",
    targetWord: "Real Madrid",
    forbiddenWords: ["Spain", "Club", "White"],
  },
  {
    category: "global",
    targetWord: "LeBron James",
    forbiddenWords: ["Basketball", "NBA", "King"],
  },
  {
    category: "global",
    targetWord: "Michael Jordan",
    forbiddenWords: ["Basketball", "NBA", "Bulls"],
  },
  {
    category: "global",
    targetWord: "Serena Williams",
    forbiddenWords: ["Tennis", "Champion", "Sister"],
  },
  {
    category: "global",
    targetWord: "Usain Bolt",
    forbiddenWords: ["Runner", "Fast", "Jamaica"],
  },
  {
    category: "global",
    targetWord: "Anthony Joshua",
    forbiddenWords: ["Boxing", "Nigeria", "Champ"],
  },
  {
    category: "global",
    targetWord: "World Cup",
    forbiddenWords: ["Football", "FIFA", "Trophy"],
  },
  {
    category: "global",
    targetWord: "Olympics",
    forbiddenWords: ["Games", "Gold", "Medal"],
  },
  {
    category: "global",
    targetWord: "Premier League",
    forbiddenWords: ["EPL", "England", "Football"],
  },
  {
    category: "global",
    targetWord: "Champions League",
    forbiddenWords: ["UEFA", "Football", "Europe"],
  },
  {
    category: "global",
    targetWord: "Black Panther",
    forbiddenWords: ["Wakanda", "Marvel", "Chadwick"],
  },
  {
    category: "global",
    targetWord: "Avengers",
    forbiddenWords: ["Marvel", "Superheroes", "Thanos"],
  },
  {
    category: "global",
    targetWord: "Spider-Man",
    forbiddenWords: ["Web", "Peter Parker", "Marvel"],
  },
  {
    category: "global",
    targetWord: "Batman",
    forbiddenWords: ["DC", "Joker", "Gotham"],
  },
  {
    category: "global",
    targetWord: "Superman",
    forbiddenWords: ["DC", "Clark Kent", "Kryptonite"],
  },
  {
    category: "global",
    targetWord: "Wonder Woman",
    forbiddenWords: ["DC", "Amazon", "Hero"],
  },
  {
    category: "global",
    targetWord: "Game of Thrones",
    forbiddenWords: ["Dragon", "Winter", "Series"],
  },
  {
    category: "global",
    targetWord: "Squid Game",
    forbiddenWords: ["Netflix", "Korea", "Green Light"],
  },
  {
    category: "global",
    targetWord: "Money Heist",
    forbiddenWords: ["Bella Ciao", "Professor", "Netflix"],
  },
  {
    category: "global",
    targetWord: "Bridgerton",
    forbiddenWords: ["Netflix", "Period", "Romance"],
  },
  {
    category: "global",
    targetWord: "Coming to America",
    forbiddenWords: ["Eddie Murphy", "Prince", "Zamunda"],
  },
  {
    category: "global",
    targetWord: "The Lion King",
    forbiddenWords: ["Simba", "Disney", "Mufasa"],
  },
  {
    category: "global",
    targetWord: "Frozen",
    forbiddenWords: ["Elsa", "Let It Go", "Disney"],
  },
  {
    category: "global",
    targetWord: "Tom & Jerry",
    forbiddenWords: ["Cat", "Mouse", "Cartoon"],
  },
  {
    category: "global",
    targetWord: "SpongeBob",
    forbiddenWords: ["SquarePants", "Patrick", "Cartoon"],
  },
  {
    category: "global",
    targetWord: "Mickey Mouse",
    forbiddenWords: ["Disney", "Mouse", "Ears"],
  },
  {
    category: "global",
    targetWord: "James Bond",
    forbiddenWords: ["007", "Spy", "Movie"],
  },
  {
    category: "global",
    targetWord: "Harry Potter",
    forbiddenWords: ["Wizard", "Hogwarts", "Magic"],
  },
  {
    category: "global",
    targetWord: "Titanic",
    forbiddenWords: ["Ship", "Iceberg", "Jack"],
  },
  {
    category: "global",
    targetWord: "Avatar",
    forbiddenWords: ["Blue", "Movie", "Pandora"],
  },
  {
    category: "global",
    targetWord: "Barbie",
    forbiddenWords: ["Doll", "Pink", "Movie"],
  },
  {
    category: "global",
    targetWord: "Will Smith",
    forbiddenWords: ["Actor", "Slap", "Fresh Prince"],
  },
  {
    category: "global",
    targetWord: "Dwayne Johnson",
    forbiddenWords: ["The Rock", "Actor", "Wrestler"],
  },
  {
    category: "global",
    targetWord: "Kevin Hart",
    forbiddenWords: ["Comedian", "Short", "Funny"],
  },
  {
    category: "global",
    targetWord: "Leonardo DiCaprio",
    forbiddenWords: ["Actor", "Titanic", "Oscar"],
  },
  {
    category: "global",
    targetWord: "Zendaya",
    forbiddenWords: ["Actress", "Spider-Man", "Euphoria"],
  },
  {
    category: "global",
    targetWord: "Kim Kardashian",
    forbiddenWords: ["Kanye", "Reality", "Famous"],
  },
  {
    category: "global",
    targetWord: "Coca-Cola",
    forbiddenWords: ["Soda", "Drink", "Red"],
  },
  {
    category: "global",
    targetWord: "Pepsi",
    forbiddenWords: ["Soda", "Drink", "Blue"],
  },
  {
    category: "global",
    targetWord: "McDonald's",
    forbiddenWords: ["Burger", "Fries", "Big Mac"],
  },
  {
    category: "global",
    targetWord: "KFC",
    forbiddenWords: ["Chicken", "Fried", "Colonel"],
  },
  {
    category: "global",
    targetWord: "Dominos",
    forbiddenWords: ["Pizza", "Delivery", "Cheese"],
  },
  {
    category: "global",
    targetWord: "Indomie",
    forbiddenWords: ["Noodles", "Instant", "Hungry"],
  },
  {
    category: "global",
    targetWord: "Nike",
    forbiddenWords: ["Just Do It", "Shoes", "Swoosh"],
  },
  {
    category: "global",
    targetWord: "Adidas",
    forbiddenWords: ["Stripes", "Shoes", "Sport"],
  },
  {
    category: "global",
    targetWord: "Gucci",
    forbiddenWords: ["Fashion", "Luxury", "Italy"],
  },
  {
    category: "global",
    targetWord: "Louis Vuitton",
    forbiddenWords: ["LV", "Bag", "Luxury"],
  },
  {
    category: "global",
    targetWord: "Rolex",
    forbiddenWords: ["Watch", "Expensive", "Time"],
  },
  {
    category: "global",
    targetWord: "Toyota",
    forbiddenWords: ["Car", "Corolla", "Camry"],
  },
  {
    category: "global",
    targetWord: "Mercedes Benz",
    forbiddenWords: ["Car", "Luxury", "German"],
  },
  {
    category: "global",
    targetWord: "Range Rover",
    forbiddenWords: ["Car", "SUV", "Luxury"],
  },
  {
    category: "global",
    targetWord: "BMW",
    forbiddenWords: ["Car", "German", "Speed"],
  },
  {
    category: "global",
    targetWord: "Lexus",
    forbiddenWords: ["Car", "Toyota", "Luxury"],
  },
  {
    category: "global",
    targetWord: "Bible",
    forbiddenWords: ["Book", "Christian", "God"],
  },
  {
    category: "global",
    targetWord: "Quran",
    forbiddenWords: ["Book", "Muslim", "Allah"],
  },
  {
    category: "global",
    targetWord: "Church",
    forbiddenWords: ["Sunday", "Pray", "Building"],
  },
  {
    category: "global",
    targetWord: "Mosque",
    forbiddenWords: ["Friday", "Pray", "Building"],
  },
  {
    category: "global",
    targetWord: "Wedding",
    forbiddenWords: ["Bride", "Groom", "Ring"],
  },
  {
    category: "global",
    targetWord: "Birthday",
    forbiddenWords: ["Cake", "Year", "Party"],
  },
  {
    category: "global",
    targetWord: "Valentine",
    forbiddenWords: ["Love", "Red", "February"],
  },
  {
    category: "global",
    targetWord: "Christmas",
    forbiddenWords: ["December", "Jesus", "Santa"],
  },
  {
    category: "global",
    targetWord: "School",
    forbiddenWords: ["Study", "Teacher", "Class"],
  },
  {
    category: "global",
    targetWord: "Exam",
    forbiddenWords: ["Test", "Write", "Pass"],
  },
  {
    category: "global",
    targetWord: "University",
    forbiddenWords: ["Degree", "School", "Campus"],
  },
  {
    category: "global",
    targetWord: "Doctor",
    forbiddenWords: ["Hospital", "Medicine", "Sick"],
  },
  {
    category: "global",
    targetWord: "Lawyer",
    forbiddenWords: ["Court", "Judge", "Case"],
  },
  {
    category: "global",
    targetWord: "Police",
    forbiddenWords: ["Arrest", "Uniform", "Station"],
  },
  {
    category: "global",
    targetWord: "Visa",
    forbiddenWords: ["Passport", "Travel", "Embassy"],
  },
  {
    category: "global",
    targetWord: "Passport",
    forbiddenWords: ["Travel", "Book", "ID"],
  },
  {
    category: "global",
    targetWord: "Airport",
    forbiddenWords: ["Plane", "Travel", "Fly"],
  },
  {
    category: "global",
    targetWord: "Lagos",
    forbiddenWords: ["City", "Nigeria", "Traffic"],
  },
  {
    category: "global",
    targetWord: "London",
    forbiddenWords: ["UK", "England", "Queen"],
  },
  {
    category: "global",
    targetWord: "Dubai",
    forbiddenWords: ["UAE", "Travel", "Shopping"],
  },
  {
    category: "global",
    targetWord: "New York",
    forbiddenWords: ["USA", "City", "America"],
  },
  {
    category: "global",
    targetWord: "Canada",
    forbiddenWords: ["Country", "Cold", "Japa"],
  },
  {
    category: "global",
    targetWord: "China",
    forbiddenWords: ["Country", "Asia", "Goods"],
  },
  {
    category: "global",
    targetWord: "Rice",
    forbiddenWords: ["Food", "White", "Grain"],
  },
  {
    category: "global",
    targetWord: "Beans",
    forbiddenWords: ["Food", "Protein", "Eat"],
  },
  {
    category: "global",
    targetWord: "Chicken",
    forbiddenWords: ["Bird", "Meat", "Food"],
  },
  {
    category: "global",
    targetWord: "Fish",
    forbiddenWords: ["Water", "Swim", "Food"],
  },
  {
    category: "global",
    targetWord: "Water",
    forbiddenWords: ["Drink", "Liquid", "Thirsty"],
  },
  {
    category: "global",
    targetWord: "Bread",
    forbiddenWords: ["Food", "Loaf", "Flour"],
  },
  {
    category: "global",
    targetWord: "Egg",
    forbiddenWords: ["Chicken", "Fry", "Boil"],
  },
  {
    category: "global",
    targetWord: "Money",
    forbiddenWords: ["Cash", "Spend", "Buy"],
  },
  {
    category: "global",
    targetWord: "Dollar",
    forbiddenWords: ["Money", "USA", "Currency"],
  },
];
